/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal3;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;
/**
 *
 * @author fernada
 */
public final class ConsultaCupon extends javax.swing.JFrame {
    public ConsultaCupon(){
         initComponents();
         setLocationRelativeTo(null); 
        DefaultTableModel t = new DefaultTableModel(
        new String[]{"Código", "Valor", "Tipo", "Fecha de Vencimiento"},
        0 // Importante: inicializa con 0 
    );

    // ✅ Asignar el modelo a la tabla
    jTable1.setModel(t);

    // ✅ Configurar el combo box con tipos de cupón
    jComboBox1.removeAllItems();
    jComboBox1.addItem("Porcentaje");
    jComboBox1.addItem("Monto");

    // ✅ Llenar la tabla
    pintarTabla();
}
    /**
     * Creates new form ConsultaCupon
     */
    
    public void pintarTabla() {
     DefaultTableModel modeloTabla = (DefaultTableModel) jTable1.getModel();
    modeloTabla.setRowCount(0); // Limpiar tabla

    for (Cupon cupon : Proyectofinal3.cupones) {
        String descuentoTexto;

        if ("porcentaje".equalsIgnoreCase(cupon.getTipo())) {
            descuentoTexto = String.format("%.0f", cupon.getDescuento()) + "%";
        } else {
            descuentoTexto = String.format("%.2f", cupon.getDescuento());
        }

        modeloTabla.addRow(new Object[]{
            cupon.getCodigo(),
            descuentoTexto,
            cupon.getTipo().equalsIgnoreCase("porcentaje") ? "Porcentaje" : "Monto", // ✅ Mostrar tipo
            cupon.getFechaVencimiento()
        });
    }
}
  public void actualizarTabla() {
    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
    modelo.setRowCount(0); // Limpiar la tabla

    for (Cupon cupon : Proyectofinal3.cupones) {
        String tipoMostrar = cupon.getTipo().equalsIgnoreCase("porcentaje") ? "Porcentaje" : "Monto";
        String descuentoTexto = cupon.getTipo().equalsIgnoreCase("porcentaje")
                ? String.format("%.0f%%", cupon.getDescuento())
                : String.format("%.2f", cupon.getDescuento());

        Object[] fila = {
            cupon.getCodigo(),
            tipoMostrar,
            descuentoTexto,
            cupon.getFechaVencimiento().toString()
        };
        modelo.addRow(fila);
    }
}

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("MathJax_Main", 0, 18)); // NOI18N
        jLabel1.setText("Registro de Cupones");

        jTable1.setFont(new java.awt.Font("Liberation Serif", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTable1.setSelectionForeground(new java.awt.Color(242, 242, 242));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("C059", 0, 14)); // NOI18N
        jLabel2.setText("Codigo:");

        jButton1.setFont(new java.awt.Font("Liberation Serif", 0, 16)); // NOI18N
        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Liberation Serif", 0, 16)); // NOI18N
        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Liberation Serif", 0, 16)); // NOI18N
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("C059", 0, 14)); // NOI18N
        jLabel3.setText("Valor:");

        jLabel4.setFont(new java.awt.Font("C059", 0, 14)); // NOI18N
        jLabel4.setText("Fecha de vencimiento:");

        jButton4.setFont(new java.awt.Font("Liberation Serif", 0, 16)); // NOI18N
        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)))
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                .addComponent(jTextField2))
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int modificar = jTable1.getSelectedRow();

    if (modificar > -1) {
        Cupon cupon = Proyectofinal3.cupones.get(modificar);

        jTextField1.setText(cupon.getCodigo());          
        jTextField2.setText(String.valueOf(cupon.getDescuento()));  

        String fechaVencimiento = cupon.getFechaVencimiento().toString();  
        jTextField3.setText(fechaVencimiento);

        // ✅ Seleccionar el tipo en el combo box
        if ("porcentaje".equalsIgnoreCase(cupon.getTipo())) {
            jComboBox1.setSelectedItem("Porcentaje");
        } else {
            jComboBox1.setSelectedItem("Monto");
        }

    } else {
        JOptionPane.showMessageDialog(this, "Seleccione un cupón para modificar.");
}        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     int modificar = jTable1.getSelectedRow();  // Obtener la fila seleccionada

if (modificar > -1) {
    Cupon cupon = Proyectofinal3.cupones.get(modificar);

    // Actualizar el código del cupón
    cupon.setCodigo(jTextField1.getText());  // Código del cupón

    // Obtener y actualizar el descuento
    double valor = Double.parseDouble(jTextField2.getText());  // Obtener el descuento
    cupon.setDescuento(valor);  // Establecer el descuento

    // Obtener y actualizar el tipo del cupón (porcentaje o monto)
    String tipo = (String) jComboBox1.getSelectedItem();  // Obtener el tipo desde el combo box
    if ("Porcentaje".equalsIgnoreCase(tipo)) {
        cupon.setTipo("porcentaje");  // Establecer tipo como "porcentaje"
    } else {
        cupon.setTipo("monto");  // Establecer tipo como "monto"
    }

    // Validar y convertir la fecha de vencimiento
    try {
        String fechaTexto = jTextField3.getText();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate fechaVencimiento = LocalDate.parse(fechaTexto, formatter);  // Convertir texto a LocalDate
        cupon.setFechaVencimiento(fechaVencimiento);  // Establecer la fecha en el cupón
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Fecha inválida. Usa el formato YYYY-MM-DD.", "Error", JOptionPane.ERROR_MESSAGE);
        return;  // Salir si la fecha es inválida
    }

    // Actualizar la tabla con los nuevos datos
    pintarTabla();

    // Mostrar mensaje de éxito
    JOptionPane.showMessageDialog(this, "Cambio guardado con éxito.");
} else {
    // Mostrar mensaje si no se seleccionó ninguna fila
    JOptionPane.showMessageDialog(this, "Seleccione un cupón para guardar los cambios.");
}                                           
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      int filaSeleccionada = jTable1.getSelectedRow();
    
    if (filaSeleccionada > -1) {
        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar este cupón?");
        
        if (confirmacion == JOptionPane.YES_OPTION) {
            Proyectofinal3.cupones.remove(filaSeleccionada);
            pintarTabla(); // Actualiza la tabla después de borrar
            JOptionPane.showMessageDialog(this, "Cupón eliminado");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione un cupón para borrar");

    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
